name: Project Tests

on:
  push:
    branches:
      - main
    paths:
      - **

jobs:
  project-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout exercise feedback
        uses: actions/checkout@v4
        with:
          repository: jvalue/made-exercise-feedback
          path: grading    

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      # Install jayvee
      - name: Set up Jayvee
        run: |
          ./grading/ci/setup_jayvee.sh

      - name: Project tests
        id: ex_feedback
        run: |
          ./project/tests.sh
